"""device_type required

Revision ID: 9ebb4c34ae2e
Revises: fd9e4c018580
Create Date: 2026-05-17 20:38:38.739504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ebb4c34ae2e'
down_revision: Union[str, Sequence[str], None] = 'fd9e4c018580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('floor_devices', 'device_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('floor_devices', 'device_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
