"""initial

Revision ID: e7d5bc656a63
Revises: 
Create Date: 2026-05-04 13:24:54.035475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e7d5bc656a63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('building', sa.String(length=255), nullable=True),
    sa.Column('floorplan_s3_key', sa.String(length=1024), nullable=True),
    sa.Column('scale_factor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floor_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('dev_eui', sa.String(length=16), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.Column('is_stationary', sa.Boolean(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'dev_eui', name='uq_floor_device')
    )
    op.create_index(op.f('ix_floor_devices_dev_eui'), 'floor_devices', ['dev_eui'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_floor_devices_dev_eui'), table_name='floor_devices')
    op.drop_table('floor_devices')
    op.drop_table('floors')
    # ### end Alembic commands ###
