"""building model

Revision ID: fd9e4c018580
Revises: e7d5bc656a63
Create Date: 2026-05-07 09:59:38.634255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd9e4c018580'
down_revision: Union[str, Sequence[str], None] = 'e7d5bc656a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('uq_floor_device'), 'floor_devices', type_='unique')
    op.drop_index(op.f('ix_floor_devices_dev_eui'), table_name='floor_devices')
    op.create_index(op.f('ix_floor_devices_dev_eui'), 'floor_devices', ['dev_eui'], unique=True)
    op.drop_constraint(op.f('floor_devices_floor_id_fkey'), 'floor_devices', type_='foreignkey')
    op.create_foreign_key(None, 'floor_devices', 'floors', ['floor_id'], ['id'])
    op.add_column('floors', sa.Column('floorplan_key', sa.String(length=1024), nullable=False))
    op.add_column('floors', sa.Column('building_id', sa.Integer(), nullable=False))
    op.alter_column('floors', 'scale_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'floors', 'buildings', ['building_id'], ['id'])
    op.drop_column('floors', 'building')
    op.drop_column('floors', 'floorplan_s3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floors', sa.Column('floorplan_s3_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('floors', sa.Column('building', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'floors', type_='foreignkey')
    op.alter_column('floors', 'scale_factor',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('floors', 'building_id')
    op.drop_column('floors', 'floorplan_key')
    op.drop_constraint(None, 'floor_devices', type_='foreignkey')
    op.create_foreign_key(op.f('floor_devices_floor_id_fkey'), 'floor_devices', 'floors', ['floor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_floor_devices_dev_eui'), table_name='floor_devices')
    op.create_index(op.f('ix_floor_devices_dev_eui'), 'floor_devices', ['dev_eui'], unique=False)
    op.create_unique_constraint(op.f('uq_floor_device'), 'floor_devices', ['floor_id', 'dev_eui'], postgresql_nulls_not_distinct=False)
    op.drop_table('buildings')
    # ### end Alembic commands ###
